version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test-reports
            python -m xmlrunner -o test-reports myself_test.py

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
